os:
  - linux
language: java
install: true
dist: trusty
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - MAVEN_USER_HOME=$HOME/.m2/repository/
before_install:
  - |
    if [[ $JHI_JDK = '8' ]]; then
      echo '*** Using OpenJDK 8'
    else
      echo '*** Using OpenJDK 11 by default'
      sudo add-apt-repository ppa:openjdk-r/ppa -y
      sudo apt-get update -q
      sudo apt-get install -y openjdk-11-jdk -y
      sudo update-java-alternatives -s java-1.11.0-openjdk-amd64
      java -version
    fi
  - java -version
script:
  - chmod +x gradlew
  - ./gradlew clean verify && ./gradlew check

after_success:
  - '[[ $TRAVIS_BRANCH == "master" ]] && [[ ${TRAVIS_PULL_REQUEST} == ''false'' ]] && [[ ${TRAVIS_TAG} == '''' ]] && mvn deploy -B -DskipTests -s settings.xml'
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
